### ISSUE TITLE
[FEATURE] Extension verification due TYPO3

### ISSUE THREAD

**Issue by kreidewe** [CPS-IT/handlebars#34]
To get a verification label as "Verified extension maintainer" in https://typo3.com/psl a review is required (see i.e. b13 Gmbh).

https://typo3.com/typo3-cms/verified-extensions-integrations-for-typo3/what-are-verified-extensions-integrations
https://typo3.com/contact-typo3

Are we in the condition to do a verification?

**Comment by eliashaeussler** [comment]
We discussed to not do this at the moment. Therefore, I'll close this issue for now. We can still re-open it one day if things have changed.
