### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by deleonio** [CPS-IT/handlebars#69]
### Is your feature request related to a problem?

Is it possible to combine handlebar engine, with a server-side-rendering, webcomponent? Is there a point where we can run nodejs?

### Describe the solution you'd like

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by cojaco** [comment]
The purpose of the handlebar engine is to render ".hbs" Templates via PHP. 
If you are looking for a headless approach, to be able to render SSR web-components, maybe have a look at the TYPO3 headless extensions, I'm not so sure how good this two very different approaches would mix, though.

**Comment by eliashaeussler** [comment]
Closing due to lack of feedback.
